server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: defaultUser
      password: bilge!123


authserviceconfig:
  secrets:
    secret-key: ${JAVA12_SECRETKEY}
    issuer:  ${JAVA12_ISSUER}